from parsers import Moscow, URL_MONTH
month = Moscow()
html = month.get_html(URL_MONTH)
weather_month_list = [
    f"{month.get_month(html.text)[0]['date']}: {month.get_month(html.text)[0]['weather']}",
    f"{month.get_month(html.text)[1]['date']}: {month.get_month(html.text)[1]['weather']}",
    f"{month.get_month(html.text)[2]['date']}: {month.get_month(html.text)[2]['weather']}",
    f"{month.get_month(html.text)[3]['date']}: {month.get_month(html.text)[3]['weather']}",
    f"{month.get_month(html.text)[4]['date']}: {month.get_month(html.text)[4]['weather']}",
    f"{month.get_month(html.text)[5]['date']}: {month.get_month(html.text)[5]['weather']}",
    f"{month.get_month(html.text)[6]['date']}: {month.get_month(html.text)[6]['weather']}",
    f"{month.get_month(html.text)[7]['date']}: {month.get_month(html.text)[7]['weather']}",
    f"{month.get_month(html.text)[8]['date']}: {month.get_month(html.text)[8]['weather']}",
    f"{month.get_month(html.text)[9]['date']}: {month.get_month(html.text)[9]['weather']}",
    f"{month.get_month(html.text)[10]['date']}: {month.get_month(html.text)[10]['weather']}",
    f"{month.get_month(html.text)[11]['date']}: {month.get_month(html.text)[11]['weather']}",
    f"{month.get_month(html.text)[12]['date']}: {month.get_month(html.text)[12]['weather']}",
    f"{month.get_month(html.text)[13]['date']}: {month.get_month(html.text)[13]['weather']}",
    f"{month.get_month(html.text)[14]['date']}: {month.get_month(html.text)[14]['weather']}",
    f"{month.get_month(html.text)[15]['date']}: {month.get_month(html.text)[15]['weather']}",
    f"{month.get_month(html.text)[16]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[17]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[18]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[19]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[20]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[20]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[21]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[22]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[23]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[24]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[25]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[26]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[27]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[28]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[29]['date']}: {month.get_month(html.text)[16]['weather']}",
    f"{month.get_month(html.text)[30]['date']}: {month.get_month(html.text)[16]['weather']}",
]
